// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go_rpc_probuf/probuf/math.proto

package mathrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MathRequest struct {
	M1                   float32  `protobuf:"fixed32,1,opt,name=m1,proto3" json:"m1,omitempty"`
	M2                   float32  `protobuf:"fixed32,2,opt,name=m2,proto3" json:"m2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MathRequest) Reset()         { *m = MathRequest{} }
func (m *MathRequest) String() string { return proto.CompactTextString(m) }
func (*MathRequest) ProtoMessage()    {}
func (*MathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5653091db282031, []int{0}
}

func (m *MathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MathRequest.Unmarshal(m, b)
}
func (m *MathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MathRequest.Marshal(b, m, deterministic)
}
func (m *MathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MathRequest.Merge(m, src)
}
func (m *MathRequest) XXX_Size() int {
	return xxx_messageInfo_MathRequest.Size(m)
}
func (m *MathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MathRequest proto.InternalMessageInfo

func (m *MathRequest) GetM1() float32 {
	if m != nil {
		return m.M1
	}
	return 0
}

func (m *MathRequest) GetM2() float32 {
	if m != nil {
		return m.M2
	}
	return 0
}

type MathResponse struct {
	Res                  float32  `protobuf:"fixed32,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MathResponse) Reset()         { *m = MathResponse{} }
func (m *MathResponse) String() string { return proto.CompactTextString(m) }
func (*MathResponse) ProtoMessage()    {}
func (*MathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5653091db282031, []int{1}
}

func (m *MathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MathResponse.Unmarshal(m, b)
}
func (m *MathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MathResponse.Marshal(b, m, deterministic)
}
func (m *MathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MathResponse.Merge(m, src)
}
func (m *MathResponse) XXX_Size() int {
	return xxx_messageInfo_MathResponse.Size(m)
}
func (m *MathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MathResponse proto.InternalMessageInfo

func (m *MathResponse) GetRes() float32 {
	if m != nil {
		return m.Res
	}
	return 0
}

func init() {
	proto.RegisterType((*MathRequest)(nil), "mathrpc.MathRequest")
	proto.RegisterType((*MathResponse)(nil), "mathrpc.MathResponse")
}

func init() { proto.RegisterFile("go_rpc_probuf/probuf/math.proto", fileDescriptor_e5653091db282031) }

var fileDescriptor_e5653091db282031 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xcf, 0x8f, 0x2f,
	0x2a, 0x48, 0x8e, 0x2f, 0x28, 0xca, 0x4f, 0x2a, 0x4d, 0xd3, 0x87, 0x52, 0xb9, 0x89, 0x25, 0x19,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x20, 0x76, 0x51, 0x41, 0xb2, 0x92, 0x2e, 0x17,
	0xb7, 0x6f, 0x62, 0x49, 0x46, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x10, 0x1f, 0x17, 0x53,
	0xae, 0xa1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x53, 0x10, 0x53, 0xae, 0x21, 0x98, 0x6f, 0x24, 0xc1,
	0x04, 0xe5, 0x1b, 0x29, 0x29, 0x70, 0xf1, 0x40, 0x94, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a,
	0x09, 0x70, 0x31, 0x17, 0xa5, 0x16, 0x43, 0x35, 0x80, 0x98, 0x46, 0x3e, 0x10, 0x03, 0x83, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x6c, 0x21, 0x1a, 0x9c, 0x13, 0x73, 0x92, 0x4b, 0x83, 0x0a,
	0x92, 0x85, 0x44, 0xf4, 0xa0, 0x36, 0xeb, 0x21, 0x59, 0x2b, 0x25, 0x8a, 0x26, 0x0a, 0x31, 0x5d,
	0x89, 0x21, 0x89, 0x0d, 0xec, 0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0xe8, 0xc4,
	0x0f, 0xd1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MathServiceClient is the client API for MathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathServiceClient interface {
	MathCalcuRpc(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error)
}

type mathServiceClient struct {
	cc *grpc.ClientConn
}

func NewMathServiceClient(cc *grpc.ClientConn) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) MathCalcuRpc(ctx context.Context, in *MathRequest, opts ...grpc.CallOption) (*MathResponse, error) {
	out := new(MathResponse)
	err := c.cc.Invoke(ctx, "/mathrpc.MathService/MathCalcuRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServiceServer is the server API for MathService service.
type MathServiceServer interface {
	MathCalcuRpc(context.Context, *MathRequest) (*MathResponse, error)
}

// UnimplementedMathServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMathServiceServer struct {
}

func (*UnimplementedMathServiceServer) MathCalcuRpc(ctx context.Context, req *MathRequest) (*MathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MathCalcuRpc not implemented")
}

func RegisterMathServiceServer(s *grpc.Server, srv MathServiceServer) {
	s.RegisterService(&_MathService_serviceDesc, srv)
}

func _MathService_MathCalcuRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).MathCalcuRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathrpc.MathService/MathCalcuRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).MathCalcuRpc(ctx, req.(*MathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MathService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mathrpc.MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MathCalcuRpc",
			Handler:    _MathService_MathCalcuRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_rpc_probuf/probuf/math.proto",
}
